### ISSUE TITLE
Request from getusppe.org state pages: zoom map to state on desktop OS

### ISSUE THREAD

**Issue by r-pop** [r-pop/findthemasks#155]
Customer is Carl Mueller on the big slack. Is this feasible?

**Comment by r-pop** [comment]
@susanashlock

**Comment by susanashlock** [comment]
Sounds like Nate Burt might be working on this.  To get clarity on what the request is: is the request that we default to zooming in on the state that the user is in?  If so, I'm not sure that that's ideal behavior.  e.g. consider someone who lives in NY city.  We currently zoom in to the 3 nearest dropoff sites.  I'd be inclined to bump up this number to ~10, rather than zoom to state level.

But I might just not understand what the request really is.

**Comment by graemer** [comment]
@susanashlock this is in support of https://getusppe.org/portfolio/utah/ pages.

These use give.html?state=ut so we do two things: 
1. Zoom to the state-level (this is merged, though it seems a little too zoomed out)
2. Filter out all map locations other than those in UT... @nburt is picking this up.

**Comment by nburt** [comment]
I picked up a sane zoom that worked for all states (except a special case for Alaska) to start. I can fine tune them a bit manually without too much effort so that. they aren't too zoomed out and will have a pr up soon

**Comment by nburt** [comment]
https://github.com/r-pop/findthemasks/pull/168

**Comment by patricknelson** [comment]
Done, can close 😄 awesome work @nburt

**Comment by volantwish** [comment]
Verified! Closing.
