### ISSUE TITLE
Site reportedly doesn't render on Microsoft Edge

### ISSUE THREAD

**Issue by rezendi** [r-pop/findthemasks#66]
Report from a nurse friend in Maine. Not sure which version at the moment - have enquired.

**Comment by rezendi** [comment]
Update: "Microsoft edge 42.17134.1098.0" "Microsoft edge HTML 17.17134"

**Comment by r-pop** [comment]
If someone has Windows and can repro, please let us know here.

**Comment by r-pop** [comment]
@marcpopmsft does this repro for you? This is EdgeHTML Edge, not Chromium Edge, right?

**Comment by cchang-adi** [comment]
Repro'd on Edge on Windows 10. Filters don't work - clicking doesn't hide other states information.

**Comment by volantwish** [comment]
On Edge, I'm not seeing the map, filters, or list display at all...the error in the console is `Object doesn't support property or method 'flat'`, pointing at [this line](https://github.com/r-pop/findthemasks/blob/a83cdc635af6cf3246868ac0302760455530d6d0/public/locations-list-map.js#L236). We're going to need to replace the arrow functions throughout the JS for IE/Edge support. If anyone's picking this up, please comment, otherwise, I can take a look at this tomorrow.

**Comment by volantwish** [comment]
Oops, was looking at the wrong line. I've got a fix for Edge. There's still more work to do for older IE, though.

**Comment by vdalal** [comment]
Site renders fine with:
* Microsoft Edge 80.0.xyz

**Comment by r-pop** [comment]
Great! I think this was for EdgeHTML Edge, and volantwish fixed it.
